version: '3.5'
services:

  collaboration-container:
    container_name: product-service
    image: product-service-api
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    ports:
      - 8080:8080
    networks:
      - my-network

networks:
  my-network: