CREATE TABLE PRODUCT (
  id            INT AUTO_INCREMENT PRIMARY KEY,
  name          VARCHAR(64) NOT NULL,
  currentPrice  DOUBLE NOT NULL,
  lastUpdate    TIMESTAMP NOT NULL
);

CREATE TABLE USER_DETAILS(
    id          INT AUTO_INCREMENT PRIMARY KEY,
    userName    VARCHAR(50) NOT NULL,
    password    VARCHAR(150) NOT NULL
);